lvim.leader = 'space'
lvim.keys.normal_mode['ss'] = ':split<cr>'
lvim.keys.normal_mode['sv'] = ':vsplit<cr>'
lvim.keys.normal_mode['+'] = '<C-a>'
lvim.keys.normal_mode['-'] = '<C-x>'
lvim.keys.normal_mode['<C-a>'] = 'gg<S-V>G'
lvim.builtin.which_key.mappings['q'] = { '<cmd>lua smart_quit()<CR>', 'Quit' }
lvim.builtin.which_key.mappings['lg'] = { '<cmd>Lspsaga goto_definition<CR>', 'Go to definition' }
lvim.builtin.which_key.mappings['lp'] = { '<cmd>Lspsaga peek_definition<CR>', 'Peek definition' }
lvim.builtin.which_key.mappings['la'] = { '<cmd>Lspsaga code_action<CR>', 'Code action' }
lvim.builtin.which_key.mappings['lF'] = { '<cmd>Lspsaga lsp_finder<CR>', 'Finder' }
lvim.builtin.which_key.mappings['lh'] = { '<cmd>Lspsaga hover_doc<CR>', 'Hover Doc' }
lvim.builtin.which_key.mappings['nw'] = { '<cmd>Neorg workspace notes<cr>', 'Open Neorg Workspace' }
lvim.builtin.which_key.mappings['nr'] = { '<cmd>Neorg return<cr>', 'Return Neorg' }
lvim.builtin.which_key.mappings['nn'] = { '<cmd>Neorg toggle-concealer<cr>', 'Toggle Concealer' }
